---
title: "CAPITOLO 2 - QUADRO PSICOBIOLOGICO E TRATTAMENTI FARMACOLOGICI PER L’AD"
---

## 2.1 CORRELATI PSICOBIOLOGICI

Analizzare nello specifico cosa accade a livello biologico e fisiologico nel cervello dell’individuo che ha sviluppato la malattia d’Alzheimer è tutt’ora ambito di ampia ricerca per la neurologia e la neuropsicologia. Per quanto siano stati delineati alcuni fattori precisi che concorrono alla malattia, le modalità con cui inizia e si conforma la cascata di eventi sono ancora per lo più ignote. Studi su ciò che a livello biologico e cellulare porta al quadro clinico della malattia di Alzheimer sono ancora in corso, tanto che attualmente è possibile trovare in letteratura una pletora di articoli che offrono più di una singola visione interpretativa della malattia.

### 2.1.1. IPOTESI AMILOIDEA

Fra le teorie più accreditate vi è quella dell’ipotesi amiloidea, supportata dal 1991 con la scoperta del gene dell’APP (Amyloid Precursor Protein, proteina precorritrice della beta-amiloide) sul cromosoma 21 da parte di J. Hardy e D. Allsop (1991). L’APP è una glicoproteina transmembrana che si trova in molte cellule del corpo umano, in particolare nella sezione delle sinapsi dei neuroni (Chen et al., 2017), implicata nella regolazione della riparazione e formazione delle stesse (Priller et al., 2006), nell’induzione e nel mantenimento della plasticità sinaptica (Turner et al., 2003) e in altri processi metabolici neuronali (Turner et al., 2003; O’Brien & Wong, 2011).

Il clivaggio dell’APP incide sulle modalità con cui si sviluppa l’AD (Figura 6): l’azione della proteasi α-secretasi avvia un processo non-amiloidogenico, per cui non si avrà formazione delle placche amiloidi ma anzi effetti benefici per l’individuo, come il mantenimento delle connessioni sinaptiche, la crescita dei dendriti e un rallentamento del programma suicida dei neuroni (Bredesen, 2022, p. 83); di contrario, tramite l’azione della proteasi β-secretasi, si instaura una catena di eventi che si conclude con la formazione delle placche amiloidi, secondo il processo amiloidogenico (Chen et al., 2017).

![Adattato da Chen et al. (2017). Il percorso non-amilodogenico dell’APP consiste nella primaria azione dell’α-secretasi, che genera l’N-terminale sAPPα e il dominio intramembrana CTFα/C83, il quale viene ulteriormente diviso dall’azione della γ-secretasi in P3 e il dominio intracellulare AICD. Il percorso amilodogenico dell’APP consiste nell’azione congiunta della β-secretasi, che seziona l’APP in sAPPβ e CTFβ/C99, e della γ-secretasi che, in ultima analisi, forma il peptide amiloide Aβ extracellulare (con tendenza ad assemblarsi in placche) e l’intracellulare AICD.](figures/ipotesi_amiloidea.png){fig-align="center"}

Seguendo il percorso amiloidogenico quindi, la β-secretasi taglia inizialmente l’APP a livello del dominio N-terminale in due frammenti, uno extramembrana definito sAPPβ, che diminuisce l’adesione intercellulare, incrementa la crescita degli assoni (Chasseigneaux et al., 2011; Chasseigneaux & Allinquant, 2012) e stimola le microglia (Barger & Harmon, 1997), e uno intramembrana definito CTFβ o C99, probabilmente coinvolto nell’insorgenza dei livelli anormali di colesterolo extracellulare (Montesinos et al., 2020). In seguito, il dominio C-terminale da 99 amminoacidi (C99) generato dall’azione della β-secretasi viene ulteriormente tagliato dall’azione della γ-secretasi (composta da quattro proteine, fra cui la nicastrina, PEN-2, APH-1 e la presenilina (Kaether et al., 2006; O’Brien & Wong, 2011; Chen et al., 2017)) nell’intracellulare AICD e nelle forme finali del peptide amiloide extracellulare in compartimenti endocitici/vescicole endocitiche, variando in grandezza con catene da 39 a 43 amminoacidi (Turner et al., 2003), le più comuni e maggiormente implicate con l’insorgenza delle placche essendo Aβ1-40 e Aβ1-42 (Kaether et al., 2006; Chen et al., 2017). Quest’ultimo è valutato come più tossico e usato come biomarker per la diagnosi di AD (Ahmed et al., 2021). 

I peptidi amiloidi non sono di per sé neurotossici, soprattutto se a basse concentrazioni che non permettono l’aggregazione di oligomeri (Duyckaerts et al., 2009; Chasseigneaux & Allinquant, 2012), ma, a determinate condizioni, riescono ad associarsi e a formare quelle che sono comunemente definite “placche amiloidi” o “placche senili”. L’accumulo di monomeri di Aβ1-42 e Aβ1-40 in placche soprattutto nelle regioni dell’ippocampo, amigdala e corteccia cerebrale (Chen et al., 2017), coinvolte nella memoria e controllo delle emozioni, altera il normale funzionamento sinaptico, specialmente per i neuroni che producono serotonina e noradrenalina (Chen et al., 2017; Breijyeh & Karaman, 2020). 

### 2.1.2. IL RUOLO DELLA PROTEINA TAU

Parallelamente all’ipotesi amiloidea, negli ultimi decenni si è fatta sempre più forte l’ipotesi che anche all’interno dei neuroni avvengano dei processi che incidono sulla neurodegenerazione e sul normale funzionamento neuronale. In particolare, come già descritto da Alois Alzheimer nel 1907, oltre alle placche amiloidi sono presenti a livello microscopico all’interno della cellula cerebrale degli ammassi neurofibrillari della proteina tau iperfosforilata. La proteina tau è una proteina assonica che, in condizioni fisiologiche, stabilizza i microtubuli, responsabili del mantenimento della struttura (Guo et al., 2017), ma se iperfosforilata, come avviene in seguito all’eccessiva attivazione dell’enzima chinasi e fosfatasi causata dall’aggregazione di Aβ (Chen et al., 2017), comporta l’instaurarsi di taupatie, con conseguente accumulo di ammassi neurofibrillari intracellulari, principalmente nell’ippocampo e nella corteccia entorinale (Duyckaerts et al., 2009). Le conseguenze di questo accumulo riguarderebbero la dissociazione delle unità microtubulari, con conseguente perdita di integrità assonale, e influenze sulla plasticità sinaptica (Drechsel et al., 1992; Combs et al., 2019; Kent et al., 2020; Muralidar et al., 2020).

### 2.1.3. LE MUTAZIONI DEI GENI DELLE PRESENILINE

Un’altra linea di studio è quella che riguarda le mutazioni dei geni PSEN1 (sul cromosoma 14) e PSEN2 (sul cromosoma 1) che codificano rispettivamente le proteine presenilina 1 e presenilina 2. Le preseniline sono una famiglia di proteine transmembrana che, in seguito a modificazioni post-trasduzionali, si dividono in frammenti che costituiscono il complesso dell’enzima γ-secretasi congiuntamente ad altre proteine (per un approfondimento, consultare Takasugi et al., 2003), implicato nella produzione dei peptidi beta-amiloide Aβ. Mutazioni nei geni PSEN1 e PSEN2 aumentano i livelli di attività della γ-secretasi, ultimando in un’elevata produzione di beta-amiloide in tutte le sue specie o nella produzione di forme di Aβ prone ad aggregazione, ovvero Aβ1-40 e Aβ1-42 (Lanoiselée et al., 2017; Breijyeh & Karaman, 2020). Uno studio del 2017 da parte di Lanoiselée e colleghi ha confermato la patogenicità delle mutazioni dei geni PSEN1, PSEN2 e APP per il 77% di 90 casi di mutazioni riconosciuti nel campione.

## 2.2 TRATTAMENTI FARMACOLOGICI PER L’AD

Purtroppo, ancor’oggi non esistono cure o farmaci in grado di arrestare l’avanzata dell’AD o quantomeno annullarne i suoi effetti. Nonostante ciò, gli avanzamenti nella ricerca scientifica hanno permesso di delineare due vie di azione nel trattamento dell’AD: farmaci che alterano la naturale evoluzione della malattia e farmaci che mitigano temporaneamente alcuni sintomi della demenza da Alzheimer (Alzheimer’s Association, 2024).

### 2.2.1 TRATTAMENTI FISIOPATOLOGICI

Con riferimento al 19 luglio 2024, l’agenzia federale statunitense della regolamentazione dei prodotti alimentari e farmaceutici (FDA – Food and Drug Administration) ha approvato l’utilizzo di due trattamenti mirati agli aspetti prettamente biologici della AD (disease-modifying drugs). Tali farmaci intervengono alterando la progressione della malattia, lavorando su vari livelli e meccanismi fisiopatologici (Breijyeh & Karaman, 2020), principalmente facendo riferimento all’ipotesi della cascata amiloidea: lo scopo generale è intervenire quanto prima possibile durante la fase preclinica, in modo da avere una maggior possibilità di cambiare le traiettorie della malattia dalla neurodegenerazione che essa comporta (Long & Holtzman, 2019). 

Il numero estremamente basso di terapie che si focalizzano proprio sugli aspetti biologici della malattia è causato dalla difficoltà di molti farmaci a superare la fase 3 di approvazione (Long & Holtzman, 2019): di fatto il 99% dei nuovi farmaci sviluppati fra il 2002 e il 2014 non ha mostrato effetti positivi (Monteiro et al., 2023). Attualmente, come data di riferimento il 1 gennaio 2024, 127 farmaci sono testati per il trattamento dell’Alzheimer, di cui il 76% indirizzate a modificare il decorso della malattia (Cummings et al., 2024). 

Nonostante i grandi passi in avanti nella ricerca sui meccanismi farmacologici per rallentare o bloccare il declino biologico della malattia, i risultati discreti dei farmaci che lavorano contro la β-amiloide dimostrano come l’ipotesi della cascata amiloidea non sia l’unica effettiva pista eziopatogenetica per l’AD (Fedele, 2023), per cui è necessario riuscire ad integrare diverse modalità di intervento e trattamento che guardino più in grande rispetto alle possibili cause della malattia.

#### ADUCANUMAB (ADUHELM®)

L’Aducanumab è un anticorpo monoclonale umano somministrato per iniezione endovenosa che rivolge la sua azione contro forme solubili e insolubili di aggregati di β-amiloide, riducendone i livelli e rallentando il declino clinico (Sevigny et al., 2016). Biogen, la casa farmaceutica che ha sviluppato questo farmaco sotto il nome Aduhelm, ha confermato che tale trattamento riduce i livelli di amiloide nel cervello, permettendo la sua approvazione dalla FDA nel giugno 2021, mentre l’EMA (European Medicines Agency) non ne ha permesso la commercializzazione (Alzheimer’s Society, 2021) in seguito a vari studi che ne hanno invece screditato l’efficacia nella riduzione delle placche (European Medicines Agency, 2022; Fedele, 2023). Nonostante la capacità del farmaco di ridurre del 22% l’andamento del decadimento cognitivo (Loeffler, 2023), la Biogen tramite un comunicato del 31 gennaio 2024 ha confermato l’interruzione dello sviluppo e della commercializzazione dell’Aduhelm, riallocando le risorse nell’avanzamento dell’altro farmaco d’interesse, il Leqembi (Biogen, 2024).

#### LECANEMAB (LEQEMBI®)

Il Lecanemab è un altro anticorpo monoclonale umanizzato ricombinante di tipo immunoglobulina gamma 1 (IgG1), con maggior affinità per gli aggregati protofibrillari solubili della β-amiloide (Vitek et al., 2023). Tali aggregati rappresentano elementi di neurotossicità in quanto intervengono bloccando i meccanismi elettrofisiologici associati al funzionamento mnestico (Lord et al., 2009), la cui produzione e azione sarebbe limitata dall’azione del Lecanemab. Il farmaco si è rivelato il più efficace nel rimuovere le protofibrille della β-amiloide, riducendo del 27% il declino clinico a livello cognitivo e funzionale su un periodo di 18 mesi (Vitek et al., 2023; van Dyck et al., 2023). Per questi effetti positivi e le prospettive rosee, il farmaco Leqembi che contiene il principio attivo del Lecanemab, presentato dalle case farmaceutiche Eisai e Biogen dopo il successo delle prove della fase 3 (van Dyck et al., 2023), ha ricevuto l’approvazione alla commercializzazione dalla FDA il 6 luglio 2023 (Food and Drug Administration, 2023).

#### DONANEMAB (KISUNLA™)

Il Donanemab è un anticorpo monoclonale umanizzato capace di legarsi unicamente ai peptidi delle placche amiloidi, garantendo così la loro rimozione attraverso fagocitosi mediata dalle cellule microgliali (DeMattos et al., 2012). Il farmaco, venduto sotto il nome di Kisunla dalla casa farmaceutica Eli Lilly, si è dimostrato in grado di rallentare significativamente di circa il 35% la progressione clinica della malattia (Fedele, 2023; Loeffler, 2023), portando l’80% e il 76% della popolazione investigata nei trial, rispettivamente per i soggetti con bassi/medi livelli di tau e per quelli con livelli combinati bassi/alti, a ridurre drasticamente i livelli del peptide amiloide alla settantaseiesima settimana (Fedele, 2023; Sims et al., 2023). Questi risultati positivi e i relativi minori avvenimenti avversi (reazioni all’iniezione, edema, microemorragie (Sims et al., 2023)) hanno fatto sì che il farmaco venisse approvato per la commercializzazione da parte della FDA il 2 luglio 2024 (Food and Drug Administration, 2024).