---
title: "CAPITOLO 1 - INTRODUZIONE ALLA MALATTIA D’ALZHEIMER"
bibliography: references.bib
---

## 1.1 LA DEMENZA E LE MALATTIE NEURODEGENERATIVE

La riduzione nei tassi di fertilità e l’aumento dell’aspettativa di vita dal 1950 ad oggi (Nazioni Unite, 2007) sono in stretta correlazione con l’aumentare dell’incidenza delle demenze (Larson, 2010; WHO, 2012). La demenza è una patologia che comporta deterioramento cognitivo, ovvero l’impoverimento e la perdita di molte aree del funzionamento dell’individuo, come l’efficienza intellettiva globale, l’attenzione, l’apprendimento, il linguaggio, le capacità di problem solving e l’autonomia (Piras & Piras, 2015).

“Demenza” è un termine ombrello che definisce una condizione caratterizzata da deterioramento cognitivo cronico, progressivo e generalmente irreversibile, che interferisce con funzioni occupazionali, domestiche e sociali (Gale et al., 2018), come l’efficienza intellettiva globale, la percezione, l’attenzione e concentrazione, l’apprendimento, il linguaggio, l’orientamento (Piras & Piras, 2015).

L’etimologia della parola deriva dal latino demens, costrutto della particella de- (“via da”, “allontanamento”, “separazione”) e della parola -mens (“mente”, “animo”, “spirito”), significando prettamente un allontanamento dalla propria mente, come se l’individuo che soffre di demenza si allontana figurativamente e fisicamente da ciò che ha caratterizzato la sua vita per tutti gli anni precedenti (Sahyouni et al., 2022). Quest’aspetto della demenza era noto già in tempi antichi, con Pitagora (580/570-495 a.C.) che, nella sua divisione della vita umana in cinque stadi, affibbiò agli ultimi due un periodo di regressione delle capacità mentali, come un completo ritorno al funzionamento infantile: in questo senso, la mente appunto si è allontanata dalla personalità e funzionamento originale per imboccare una via maladattiva rispetto alla saggezza auspicabile per quell’età.

Uno studio della demenza da un punto di vista prettamente medico e scientifico si iniziò ad avere solo in tempi relativamente recenti, con lo psichiatra francese Philippe Pinel (1745-1826) che, grazie alla sua perseverante lotta contro la stigmatizzazione delle malattie mentali, fornì una prima esaustiva descrizione dei sintomi principali della demenza, quali problemi di memoria, smemorataggine, mancanza di giudizio, agitazione e un declino rapido. Lo studente prediletto di Pinel, Jean-Étienne Dominique Esquirol (1772-1840), paragonò la malattia ad “un uomo ricco diventato improvvisamente povero” per sottolineare la natura acquisita della condizione, focalizzando il suo operato sull’analisi delle cause fisiologiche della demenza, riuscendo a ridurle ad atrofia cerebrale, circonvoluzioni cerebrali separate l’un le altre, superficiali e poco profonde, più piccole soprattutto nella zona frontale, con evidenti modificazioni strutturali dei vasi sanguigni. Queste scoperte rimasero ai vertici delle interpretazioni eziologiche della demenza fino a quando, nel 1906, lo psichiatra tedesco Alois Alzheimer tenne una famosa conferenza in cui mostrò una nuova possibile eziopatogenesi per questa malattia tramite lo studio del cervello post mortem di una sua paziente cinquantenne: egli ritrovò all’esterno e all’interno delle cellule cerebrali depositi di proteine modificate, in seguito rispettivamente identificati come placche del peptide β-amiloide e ammassi neurofibrillari della proteina Tau iperfosforilata (Duyckaerts et al., 2009; Sahyouni et al., 2022). Infine, solo recentemente, nell’edizione del 2013, il DSM5 ha abbandonato il termine arcaico e stigmatizzante “demenza” per utilizzare invece un termine più consono e al passo con le più moderne scoperte nel campo, ovvero “disordine neurocognitivo maggiore” (American Psychiatric Association, 2013).

### 1.1.1 EPIDEMIOLOGIA DELLE DEMENZE

Attualmente secondo l’Organizzazione Mondiale della Sanità (OMS), più di 55 milioni di persone soffrono di demenza in tutto il mondo ed è stimato che questi dati possano triplicare nel 2050 (WHO, 2021), raggiungendo 139 milioni di casi. In generale, il tasso di casi di demenza in tutto il mondo si attesta attorno al 7% per individui con età al di sopra dei 65 anni, con percentuali leggermente maggiori (8%-10%) in paesi più sviluppati per via di maggiori aspettative di vita (Prince et al., 2013), ed inoltre colpisce il 30% della popolazione anziana oltre gli 85 anni (Graves et al., 1996). Le fasce di età maggiormente colpite variano da continente a continente: in Europa e nelle Americhe l’incidenza si attesta negli anziani fra gli 80-89 anni, in Asia fra i 75-84 e in Africa fra i 70-79 (Prince et al., 2015). Questi dati mostrano come le demenze colpiscano ad età inferiori persone provenienti da paesi più poveri, d’altronde le percentuali chiariscono meglio questa condizione: il 63% delle persone con tale patologia, infatti, vivono in paesi con basso e medio reddito, mentre il restante 37% in paesi con reddito maggiore (Prince et al., 2015).

### 1.1.2 CLASSIFICAZIONE E TIPOLOGIE

Le demenze possono avere eziologie molto diverse, nonché differiscono nella modalità con cui interferiscono nella vita dell’individuo. Di fatto, una classificazione delle demenze può essere operata solo sulla base della natura del processo eziologico, distinguendo le demenze degenerative dalle non degenerative. Questa distinzione ha valenza puramente accademica, in quanto è possibile che un paziente affetto da demenza si ritrovi con malattie multiple con cause neurodegenerative e non (Schneider et al., 2007). Per neurodegenerazione si intende ogni condizione patologica che colpisce i neuroni, nella loro struttura o funzione in specifici sistemi anatomo-funzionali del cervello umano (Przedborski et al., 2003). In linea generale, i neuroni sono colpiti nella loro comunicazione con altre cellule cerebrali, per poi essere compromesse nella loro struttura, arrivando infine alla morte (Forloni, 2021): disfunzioni delle sinapsi, dei network neuronali e il deposito di proteine alterate nel cervello sono alla base della degenerazione neuronale (Hoover et al., 2010; Kovacs, 2019; Milnerwood & Raymond, 2010; Scott et al., 2010). Oltre alla neurodegenerazione, altre cause possibili di demenza riguardano malattie cardiovascolari, disordini metabolici e nutrizionali (Gale et al., 2018).

Le malattie neurodegenerative più comuni includono la malattia di Alzheimer, il morbo di Parkinson, la malattia da prione, la sclerosi laterale amiotrofica, la malattia dei motoneuroni, la malattia di Huntington, l’atrofia muscolare spinale e l’atassia spinocerebellare (Hague, 2005; Harding et al., 2015; Klockgether et al., 2019; Martin, 1999).

Fra queste, certamente la più conosciuta, temuta e presente nella popolazione globale, rappresentando dal 60% all’80% dei casi di demenza (Alzheimer’s Association, 2023), è la malattia di Alzheimer. Questo dato da solo sottolinea il valore della ricerca nei suoi confronti, volta ad alleggerire il carico emotivo, migliorare la qualità di vita e fornire strumenti preventivi alle persone che ne sono affette e ai loro cari.

L’Alzheimer, infatti, incide non solo sulle persone affette, ma anche su tutti gli altri sistemi in cui sono inseriti: questa condizione neurologica incide sui caregivers, ovvero le persone che offrono le loro cure ai soggetti affetti, sui parenti dei malati, mentre a livello socioeconomico i costi sono ingenti, raggiungendo cifre che si aggirano nel 2023 negli USA sui 345 miliardi di dollari statunitensi (Alzheimer’s Association, 2023), mentre in Italia “il costo annuo della malattia di Alzheimer \[…\] è stimato oltre i 15 miliardi di euro. Circa l’80% sono costi diretti e indiretti che pesano su famiglia e caregiver” (Scaccabarozzi, 2023).

Riuscire a prevenire, se non idealmente curare, la malattia d’Alzheimer, porterebbe ingenti vantaggi su più livelli del sistema che si costruisce attorno al paziente malato.

## 1.2 MALATTIA DI ALZHEIMER

### 1.2.1 DEFINIZIONE
